# -*- coding: utf-8 -*-
"""cricket_player_popularity_Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18S7Fu_K_HZZc6Cv91vsKWuqiEGLp132_
"""

import numpy as np
import pandas as pd
import re
import pickle

!pip install gensim
import gensim.downloader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

df = pd.read_csv(r"/content/Cricket_Player_Popularity_updated.csv")

df.head()

df.columns

df.duplicated().sum()

df.dropna(inplace=True)

df.info()

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"@\w+", " @ ", text)
    text = re.sub(r"[^a-z@ ]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text.split()

import gensim.downloader

print(list(gensim.downloader.info()['models']))

glove = gensim.downloader.load("glove-twitter-200")

import pickle

vocabulary = set()

# Vocabulary from player names
for player in df["Player"].dropna():
    vocabulary.update(clean_text(str(player)))

embedding_lookup = {}
for word in vocabulary:
    if word in glove:
        embedding_lookup[word] = glove[word]

with open("embedding_lookup.pkl", "wb") as f:
    pickle.dump(embedding_lookup, f)

print("Saved Successfully")
print("Vocabulary Size:", len(embedding_lookup))

def sentence_vector(sentence):

    words = clean_text(sentence)

    valid_words = [word for word in words if word in glove]

    if len(valid_words)==0:

        return np.zeros(200)

    return glove.get_mean_vector(valid_words)

X = np.array(df["Player"].apply(sentence_vector).tolist())

X.shape

def get_sentiment_label(row):
    scores = {'Positive': row['Positive'], 'Neutral': row['Neutral'], 'Negative': row['Negative']}
    max_sentiment = max(scores, key=scores.get)
    return max_sentiment

df['Sentiment'] = df.apply(get_sentiment_label, axis=1)

encoder = LabelEncoder()
y = encoder.fit_transform(df["Sentiment"])

pickle.dump(encoder,open("label_encoder.pkl","wb"))

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)

X_train,X_val,y_train,y_val = train_test_split(X_train,y_train,test_size=0.20,random_state=42,stratify=y_train)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_val = scaler.transform(X_val)

X_test = scaler.transform(X_test)

pickle.dump(scaler,open("scaler.pkl","wb"))

!pip install optuna

import optuna
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Input

from tensorflow.keras.regularizers import l1_l2

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.optimizers import Nadam

from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ReduceLROnPlateau

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

import matplotlib.pyplot as plt

def objective(trial):

    learning_rate = trial.suggest_float("learning_rate",1e-5,1e-2,log=True)

    optimizer_name = trial.suggest_categorical("optimizer",["Adam","RMSprop","Nadam"])

    activation = trial.suggest_categorical("activation",["relu","tanh","elu"])

    batch_size = trial.suggest_categorical("batch_size",[32,64,128])

    n_layers = trial.suggest_int("n_layers",2,5)

    model = Sequential()

    model.add(Input(shape=(200,)))

    for i in range(n_layers):
        units = trial.suggest_categorical(f"units_{i}",[64,128,256,512])

        dropout = trial.suggest_float(f"dropout_{i}",0.10,0.50)

        reg = trial.suggest_float(f"reg_{i}",1e-6,1e-3,log=True)

        model.add(Dense(
            units=units,
            activation=activation,
            kernel_regularizer=l1_l2(reg,reg)
        ))
        model.add(BatchNormalization())

        model.add(Dropout(dropout))

    model.add(Dense(3,activation="softmax"))

    optimizer_dict = {

        "Adam":Adam(learning_rate),

        "RMSprop":RMSprop(learning_rate),

        "Nadam":Nadam(learning_rate)

    }

    model.compile(

        optimizer=optimizer_dict[optimizer_name],

        loss="sparse_categorical_crossentropy",

        metrics=["accuracy"]

    )

    early_stop = EarlyStopping(

        monitor="val_accuracy",

        patience=7,

        restore_best_weights=True,

        mode="max"
      )

    reduce_lr = ReduceLROnPlateau(

        monitor="val_loss",

        factor=0.5,

        patience=10,

        min_lr=1e-6

    )

    history = model.fit(

        X_train,

        y_train,

        validation_data=(X_val,y_val),

        epochs=100,

        batch_size=batch_size,

        callbacks=[early_stop,reduce_lr],

        verbose=0

    )

    return max(history.history["val_accuracy"])

study = optuna.create_study(

    direction="maximize",

    sampler=optuna.samplers.TPESampler(seed=42)

)

study.optimize(

    objective,

    n_trials=30,

    show_progress_bar=True

)

print("Best Validation Accuracy :")

print(study.best_trial.value)

import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.regularizers import l1_l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

best = {
    'learning_rate': 0.009415244195298792,
    'optimizer': 'Adam',
    'activation': 'relu',
    'batch_size': 128,
    'n_layers': 3,
    'units_0': 256,
    'dropout_0': 0.4819038198762265,
    'reg_0': 3.276616214882557e-06,
    'units_1': 256,
    'dropout_1': 0.3258921610124521,
    'reg_1': 2.004525492982464e-05,
    'units_2': 512,
    'dropout_2': 0.25417429799364333,
    'reg_2': 2.6570895590079712e-05
}

X_full = np.vstack((X_train, X_val))
y_full = np.concatenate((y_train, y_val))

print(X_full.shape)
print(y_full.shape)

# -----------------------------
# Build Model
# -----------------------------

model = Sequential()

model.add(Input(shape=(X_full.shape[1],)))

for i in range(best["n_layers"]):

    model.add(
        Dense(
            units=best[f'units_{i}'],
            activation=best["activation"],
            kernel_regularizer=l1_l2(
                l1=best[f'reg_{i}'],
                l2=best[f'reg_{i}']
            )
        )
    )

    model.add(BatchNormalization())

    model.add(
        Dropout(best[f'dropout_{i}'])
    )

model.add(Dense(3, activation='softmax'))

optimizer = Adam(
    learning_rate=best["learning_rate"]
)

model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

early_stop = EarlyStopping(
    monitor='val_accuracy',
    patience=8,
    mode='max',
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=10,
    min_lr=1e-6
)

history = model.fit(
    X_full,
    y_full,
    validation_split=0.1,
    epochs=100,
    batch_size=best["batch_size"],
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

loss, accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=0
)

print(f"\nTest Loss     : {loss:.4f}")
print(f"Test Accuracy : {accuracy:.4f}")

y_prob = model.predict(X_test, verbose=0)

y_pred = np.argmax(y_prob, axis=1)

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=encoder.classes_
    )
)

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=encoder.classes_
)

disp.plot(cmap="Blues")
plt.title("Confusion Matrix")
plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history['accuracy'], label='Train')

plt.plot(history.history['val_accuracy'], label='Validation')

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.title("Training Accuracy")

plt.legend()

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history['loss'], label='Train')

plt.plot(history.history['val_loss'], label='Validation')

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.title("Training Loss")

plt.legend()

plt.show()

model.save("sentiment_model.keras")

print("\nModel Saved Successfully!")